### ISSUE TITLE
Try mysqladmin ping once more

### ISSUE THREAD

**Issue by jechols** [open-oni/docker-open-oni#17]
Without the --wait flag, mysqladmin's ping will exit immediately with false, so we should be able to stuff that into the loop.  We want to get dev.sh to be strictly container setup in the long run, and remove all the SQL commands if at all possible.

It's possible that mysqladmin ping won't be good enough for our needs; if this turns out to be the case, I vote for a fairly safe command like "SHOW DATABASES" so it's clear we aren't doing anything meaningful in dev.sh.

**Comment by AndrewGearhart** [comment]
Given what I now understand of mysqladmin ping ... it won't work for our needs here. It will __only__ determine if the server is running, not if the server is accepting connections. We will need to use --wait along with an innocuous SQL statement. I like SHOW DATABASES;. I'll get that.
