### ISSUE TITLE
Integrate with docker hub

### ISSUE THREAD

**Issue by mark-cooper** [open-oni/docker-open-oni#2]
Create automated build for `openoni/open-oni`. Setup to build when commits merged to master. Admin at open-oni needs to add docker hub app.

**Comment by kestlund** [comment]
I've authorized the application. Let me know if you need me to do anything else on this end. I haven't done this before, so let me know if I need to add the repo at docker hub.

**Comment by mark-cooper** [comment]
I added the repo at Docker hub. The open-oni repository needs to enable docker integration however ... can be done via: open-oni repo at github -> settings -> webhooks -> docker

**Comment by kestlund** [comment]
Stuck in meetings all, day, just made you an owner.  I can revoke later if you'd like.

**Comment by mark-cooper** [comment]
Done. Thanks @kestlund
